---

- name: Create Atom yum repo
  yum_repository:
    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/x86_64
    description: Atom Editor repo
    gpgcheck: no
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
    name: atom
    repo_gpgcheck: yes

- name: Install Atom
  yum:
    name: atom
