---
# tasks file for ansible/install-terraform
- name: Create a Terraform directory
  file:
    path: /opt/terraform-{{ terraform_version }}
    state: directory

- name: Downloading and installing terraform "{{ terraform_version }}"
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /opt/terraform-{{ terraform_version }}
    # owner: "vagrant"
    # group: "vagrant"
    mode: u+rx
    remote_src: yes
